# Generated by Django 4.2.2 on 2023-08-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnnotationTable",
            fields=[
                (
                    "anotation_name",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("raw_gaf", models.FileField(max_length=254, upload_to="GO_tables")),
                (
                    "processed_gaf",
                    models.FileField(
                        blank=True,
                        editable=False,
                        max_length=254,
                        upload_to="GO_tables",
                    ),
                ),
                (
                    "processed_gaf_path",
                    models.CharField(blank=True, editable=False, max_length=1000),
                ),
            ],
        ),
    ]
