# Generated by Django 4.2.2 on 2023-08-31 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("enrichmentplotter", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annotationtable",
            options={"permissions": (("modify_data", "Modify GO dataset"),)},
        ),
    ]
