# Generated by Django 4.2.2 on 2023-08-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrichmentplotter", "0002_alter_annotationtable_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationtable",
            name="raw_gaf_path",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="annotationtable",
            name="processed_gaf",
            field=models.FileField(blank=True, max_length=254, upload_to="GO_tables"),
        ),
        migrations.AlterField(
            model_name="annotationtable",
            name="processed_gaf_path",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
