# Generated by Django 4.2.2 on 2023-08-31 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("enrichmentplotter", "0003_annotationtable_raw_gaf_path_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotationtable",
            name="processed_gaf",
        ),
    ]
