# Generated by Django 4.2.2 on 2023-08-31 18:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("enrichmentplotter", "0004_remove_annotationtable_processed_gaf"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListEnrichmentInput",
            fields=[
                (
                    "query_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("id_list", models.TextField()),
                ("background_list", models.TextField()),
                ("GO_set", models.CharField(max_length=200)),
                ("precalculated_datapath", models.CharField(max_length=2000)),
            ],
        ),
    ]
