# Generated by Django 4.2.2 on 2023-09-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrichmentplotter", "0005_listenrichmentinput"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listenrichmentinput",
            name="precalculated_datapath",
        ),
        migrations.AddField(
            model_name="listenrichmentinput",
            name="precalculated_datapath_background",
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="listenrichmentinput",
            name="precalculated_datapath_query",
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
