# Generated by Django 4.2.2 on 2023-09-03 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "enrichmentplotter",
            "0006_remove_listenrichmentinput_precalculated_datapath_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="listenrichmentinput",
            name="GO_set",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="enrichmentplotter.annotationtable",
            ),
        ),
    ]
