# Generated by Django 4.2.2 on 2023-09-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrichmentplotter", "0007_alter_listenrichmentinput_go_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="listenrichmentinput",
            name="precalculated_datapath_annotation",
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
