# Generated by Django 4.2.2 on 2023-09-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "enrichmentplotter",
            "0008_listenrichmentinput_precalculated_datapath_annotation",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listenrichmentinput",
            name="precalculated_datapath_background",
        ),
        migrations.RemoveField(
            model_name="listenrichmentinput",
            name="precalculated_datapath_query",
        ),
        migrations.AddField(
            model_name="listenrichmentinput",
            name="background_items",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="listenrichmentinput",
            name="query_items",
            field=models.JSONField(null=True),
        ),
    ]
