# Generated by Django 4.2.2 on 2023-09-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrichmentplotter", "0010_alter_annotationtable_processed_gaf_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationtable",
            name="processed_gaf_path",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="annotationtable",
            name="raw_gaf_path",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
