# Generated by Django 4.2.2 on 2023-09-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrichmentplotter", "0012_alter_annotationtable_processed_gaf_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationtable",
            name="gene_BP_dict",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="annotationtable",
            name="gene_CC_dict",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="annotationtable",
            name="gene_MF_dict",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="annotationtable",
            name="uniprot_BP_dict",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="annotationtable",
            name="uniprot_CC_dict",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="annotationtable",
            name="uniprot_MF_dict",
            field=models.JSONField(null=True),
        ),
    ]
