# Generated by Django 4.2.2 on 2023-09-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrichmentplotter", "0013_annotationtable_gene_bp_dict_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationtable",
            name="gene_BP_dict",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annotationtable",
            name="gene_CC_dict",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annotationtable",
            name="gene_MF_dict",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annotationtable",
            name="uniprot_BP_dict",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annotationtable",
            name="uniprot_CC_dict",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annotationtable",
            name="uniprot_MF_dict",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
