# Generated by Django 4.2.2 on 2023-09-06 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("enrichmentplotter", "0014_alter_annotationtable_gene_bp_dict_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="annotationtable",
            old_name="uniprot_BP_dict",
            new_name="protein_BP_dict",
        ),
        migrations.RenameField(
            model_name="annotationtable",
            old_name="uniprot_CC_dict",
            new_name="protein_CC_dict",
        ),
        migrations.RenameField(
            model_name="annotationtable",
            old_name="uniprot_MF_dict",
            new_name="protein_MF_dict",
        ),
    ]
