# Generated by Django 4.2.2 on 2023-09-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "enrichmentplotter",
            "0015_rename_uniprot_bp_dict_annotationtable_protein_bp_dict_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="listenrichmentinput",
            old_name="query_items",
            new_name="query_items_annotation",
        ),
        migrations.AddField(
            model_name="listenrichmentinput",
            name="GO_BP",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="listenrichmentinput",
            name="GO_CC",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="listenrichmentinput",
            name="GO_MF",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="listenrichmentinput",
            name="input_type",
            field=models.CharField(
                choices=[("Gene", "Gene"), ("Uniprot", "Uniprot ID")],
                default="Gene",
                max_length=100,
            ),
        ),
    ]
