# Generated by Django 4.2.2 on 2023-09-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "enrichmentplotter",
            "0016_rename_query_items_listenrichmentinput_query_items_annotation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="listenrichmentinput",
            name="GO_BP",
            field=models.BooleanField(),
        ),
    ]
