# Generated by Django 4.2.2 on 2023-09-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrichmentplotter", "0017_alter_listenrichmentinput_go_bp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listenrichmentinput",
            name="GO_CC",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="listenrichmentinput",
            name="GO_MF",
            field=models.BooleanField(),
        ),
    ]
