# Generated by Django 4.2.2 on 2023-09-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrichmentplotter", "0021_plotparams"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotparams",
            name="figure_size_x",
            field=models.FloatField(default=4),
        ),
        migrations.AddField(
            model_name="plotparams",
            name="figure_size_y",
            field=models.FloatField(default=8),
        ),
        migrations.AddField(
            model_name="plotparams",
            name="font_size_plot_title",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plotparams",
            name="font_size_x_labels",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plotparams",
            name="font_size_x_title",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plotparams",
            name="font_size_y_labels",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plotparams",
            name="font_size_y_title",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plotparams",
            name="max_p_value",
            field=models.FloatField(default=0.01),
        ),
        migrations.AddField(
            model_name="plotparams",
            name="min_fraction",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="plotparams",
            name="min_protein_number",
            field=models.IntegerField(default=3),
        ),
    ]
